// Loads the Item Builder's data: ItemBuilder.json (generated by the item-builder-data plugin in
// vite.config.js), fetched once per page load and prepared. The same file serves both modes.
import {ITEM_BUILDER_FILE, prepareItemBuilder} from "./itemBuilderData.js";

let cached = null;

async function fetchModel() {
    const res = await fetch(`${import.meta.env.BASE_URL}data/standard/${ITEM_BUILDER_FILE}`, {cache: "no-store"});
    if (!res.ok) throw new Error(`${ITEM_BUILDER_FILE}: HTTP ${res.status}`);
    // A dev server answers a missing file with index.html and status 200, so the parse can fail too.
    const json = await res.json().catch(() => {
        throw new Error(`${ITEM_BUILDER_FILE}: not valid JSON (file missing or not generated?)`);
    });
    return prepareItemBuilder(json);
}

// A failed load is evicted, so the next call tries again.
export function loadItemBuilder() {
    if (!cached) {
        const promise = fetchModel();
        cached = promise;
        promise.catch(() => {
            if (cached === promise) cached = null;
        });
    }
    return cached;
}
